export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const MOVE_TO_PAGE = 'MOVE_TO_PAGE';

export const ADD_CHILD = 'ADD_CHILD';

export const TODO_DISPLAY_SELECT_DAY = 'TODO_DISPLAY_SELECT_DAY';
export const TODO_DISPLAY_SELECT_KID = 'TODO_DISPLAY_SELECT_KID';
export const TODO_DISPLAY_SELECT_WEEK = 'TODO_DISPLAY_SELECT_WEEK';


export const UPDATE_TODOS = 'UPDATE_TODOS';

export const UPDATE_STAT = 'UPDATE_STAT';


export const KIDS_FORM_VALUE = 'KIDS_FORM_VALUE';
